spring:
  application:
    name: role
  datasource:
    url: jdbc:mysql://localhost:3306/user_org_system?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8071
eureka:
  host: 127.0.0.1
  port: 8090
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*